---
- name: "Install IIS"
  hosts: VM02
  tasks:
    - name: Install IIS (Web-Server and Web-Common-Http)
      ansible.windows.win_feature:
        name:
        - Web-Server
        - Web-Common-Http
        state: present