---
- name: "Deploym Helm package"
  hosts: localhost
  tasks:
    - name: Set local DNS record
      ansible.builtin.shell: echo "192.158.1.0 proget.local" >> /etc/hosts

    - name: Add chart repo
      kubernetes.core.helm_repository:
          name: proget
          repo_url: "http://proget.local/helm/demo"

    - name: Install demo Chart
      kubernetes.core.helm:
        name: nginx-demo
        namespace: default
        chart_ref: proget/demo