---
- name: "Deploym Helm package"
  hosts: localhost
  tasks:

     - name: Add chart repo
       kubernetes.core.helm_repository:
          name: bitnami
          repo_url: "https://charts.bitnami.com/bitnami"

     - name: Install demo Chart
       kubernetes.core.helm:
        name: nginx-server
        namespace: testing
        chart_ref: bitnami/nginx