---
- name: "Deploym Helm package"
  hosts: localhost
  tasks:
    - name: Set local DNS record
      ansible.builtin.shell: echo "192.158.1.0 proget.local" >> /etc/hosts

    - name: Add chart repo
      ansible.builtin.shell: helm repo add proget https://proget.local/helm/demo --ca-file ca.crt

    - name: Install demo Chart
      kubernetes.core.helm:
        name: nginx-demo
        namespace: default
        chart_ref: proget/demo