---
- name: "Deploym Helm package"
  hosts: localhost
  tasks:
     - name: Install demo Chart
       kubernetes.core.helm:
        name: nginx-server
        namespace: testing
        chart_ref: bitnami/nginx