---
- name: "Deploym Helm package"
  hosts: localhost
  tasks:

     - name: Add chart repo
       kubernetes.core.helm_repository:
          name: proget
          repo_url: "https://proget.local/helm/demo"

     - name: Install demo Chart
       kubernetes.core.helm:
        name: nginx-demo
        namespace: default
        chart_ref: proget/demo