---
- name: "Install a Docker container"
  hosts: docker
  tasks:
    - name: "Install a Docker container"
      community.docker.docker_container:
        - name: "Docker Demo"
          image: gambyseb/private:win-docker-demo-0.1
          state: started
          ports:
          - "80:80"