---
- name: "Install Docker"  
  hosts: docker
  tasks:
    - name: Install the Windows Feature 'Containers'
      ansible.windows.win_feature:
        name:
        - Containers
        state: present
      register: win_feature
    
    - name: Reboot the machine to finish the installation of the Windows feature 'Containers'
      ansible.windows.win_reboot:
      when: win_feature.reboot_required

    - name: Install the 'NuGet' package -ProviderName
      ansible.windows.win_powershell:
        script: |
          Install-PackageProvider -Name NuGet -Force

    - name: Install the Powershell module 'DockerMsftProvider'
      ansible.windows.win_powershell:
        script: |
          Install-Module -Name DockerMsftProvider -Repository PSGallery -Force
    
    - name: Install Docker'
      ansible.windows.win_powershell:
        script: |
          Install-Package -Name docker -ProviderName DockerMsftProvider -Force

    - name: Start the 'Docker' service and make sure that it has start mode 'auto'
      ansible.windows.win_service:
        name: docker
        start_mode: auto
        state: started

    # The 'Docker' Ansible module requires the Python SDK to work
    - name: "Install python"
      win_chocolatey:
        name: "python"
        version: "3.10.5"
        state: present
      when: ansible_facts['hostname'] == target_machine
    
    - name: Reboot the machine to finish the installation of Docker
      ansible.windows.win_reboot:
      when: win_feature.reboot_required
    
    - name: Install the Python Docker SDK'
      ansible.windows.win_powershell:
        script: |
          pip install docker