---
- name: "Install a Docker container"
  hosts: docker
  tasks:
    - name: "Install a Docker container"
      community.docker.docker_container:
        name: "DockerDemo"
        image: gambyseb/private:win-docker-demo-0.1
        ports:
        - "80:80"