---
- name: "Install a Docker container"
  hosts: docker
  tasks:
  community.docker.docker_container:
    - name: Install a Docker container
      image: gambyseb/private:win-docker-demo-0.1
      state: started
      ports:
      - "80:80"