---
- name: "Install Docker"  
  hosts: docker
  tasks:
    - name: Install the Windows Feature 'Containers'
      ansible.windows.win_feature:
        name:
        - Containers
        state: present
      register: win_feature
    
    - debug:
        var: win_feature.reboot_required
    
    - name: Reboot the machine wait for win_feature to be confirmed installed
      ansible.windows.win_reboot:
        test_command: 'exit (Get-WindowsFeature -Name Containers).InstallState -eq "Installed"'
      when: win_feature.reboot_required

    - name: Install the 'NuGet' package -ProviderName
      ansible.windows.win_powershell:
        script: |
          Install-PackageProvider -Name NuGet -Force

    - name: Install the Powershell module 'DockerMsftProvider'
      ansible.windows.win_powershell:
        script: |
          Install-Module -Name DockerMsftProvider -Repository PSGallery -Force
    
    - name: Install Docker'
      ansible.windows.win_powershell:
        script: |
          Install-Package -Name docker -ProviderName DockerMsftProvider

    - name: Start the 'Docker' service and make sure that it has start mode 'auto'
      ansible.windows.win_service:
        name: Docker
        start_mode: auto
        state: started