---
- name: "Test PowerShell"
  hosts: windows
  tasks:
    - name: "Test Powershell"
      ansible.windows.win_powershell:
        script: |
          Start-Process -FilePath C:\ProgramData\chocolatey\bin\choco.exe -ArgumentList "install", "-y", "website.0.1.nupkg" -Wait
      when: ansible_facts['hostname'] == target_machine